"""Regenerate `frontend/src/demo/keymapFixture.ts` from the daemon's own keymaps.

Run from the repository root with `uv run python frontend/scripts/gen_keymap_fixture.py`.

The demo lets a visitor switch keymap for real, which is only worth offering if the
chords they switch to are the ones the product ships. So the fixture is generated from
`swe_mux.keymaps` rather than written by hand, and this script is checked in - the
previous copy lived outside the repository, which meant the fixture could not be
regenerated by anyone who did not already have it.

Three things come out of the daemon rather than out of a literal here, and the third is
the reason this script was rewritten:

* the preset summaries, including each preset's own warning text;
* every preset's rule list;
* **the resolution for `host="browser"`** - what a tab actually dispatches on, which
  chords it cannot receive at all, and which it shares with the browser. The demo used to
  claim an empty `undeliverable`, which is false in a way its own Vim preset documents
  ("a browser tab closes on Ctrl+W before the page ever sees it"). A demo that draws a
  dead chord as though it were live is worse than one that does not offer the switch.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from swe_mux import keybindings, keychords, keymaps

#: What the demo declares itself to be. It runs in an iframe on the marketing site, so
#: the browser half of the host table is the honest one; `win` is simply the majority
#: reader and is stated in the payload rather than inferred.
HOST = "browser"
PLATFORM = "win"

HEADER = """// GENERATED by frontend/scripts/gen_keymap_fixture.py from the daemon's own preset
// documents (`swe_mux.keymaps`) and chord policy (`swe_mux.keychords`). Do not
// hand-edit: regenerate instead, so the demo's tmux/vim/emacs bindings - and the
// list of chords a browser tab cannot receive - stay the ones the product ships.
export const KEYMAP_FIXTURE = """


def build() -> dict[str, Any]:
    rules: dict[str, list[dict[str, Any]]] = {}
    resolution: dict[str, dict[str, Any]] = {}
    for preset_id in keymaps.preset_ids():
        preset_rules = keymaps.preset_rules(preset_id)
        rules[preset_id] = [rule.as_dict() for rule in preset_rules]
        resolved = keybindings.resolve(preset_rules, host=HOST, platform=PLATFORM)
        resolution[preset_id] = {
            "bindings": resolved.bindings,
            "undeliverable": resolved.undeliverable,
            "contested": resolved.contested,
        }
    return {
        "host": HOST,
        "platform": PLATFORM,
        "presets": keymaps.preset_summaries(),
        "rules": rules,
        "resolution": resolution,
        "policy": keychords.chord_policy(),
        "commands": [
            {"id": command_id, "label": label, "category": category}
            for command_id, label, category in keybindings.KEYBINDING_COMMANDS
        ],
    }


def main() -> None:
    target = Path(__file__).resolve().parents[1] / "src" / "demo" / "keymapFixture.ts"
    body = json.dumps(build(), indent=1, ensure_ascii=False)
    # LF endings and a trailing newline, matching every other source file here: the
    # generator runs on Windows and Python would otherwise translate them on write.
    target.write_text(f"{HEADER}{body}\n", encoding="utf-8", newline="\n")
    print(f"wrote {target}")


if __name__ == "__main__":
    main()
