/**
 * Headless parity + latency bench for the Smart Turn v3 chain.
 *
 *   uv run python tools/fetch_smart_turn.py     # once, ~8 MB of weights
 *   npm --prefix frontend run bench:smart-turn
 *
 * Two things, neither of which the browser lab can tell you on its own:
 *
 *   PARITY - the TypeScript mel extractor against the real Python stack
 *   (HuggingFace `WhisperFeatureExtractor`) on the same audio. Every stage of
 *   this preprocessing chain fails silently: a transposed axis, a non-periodic
 *   Hann window, or the wrong mel normalization all yield a full-looking
 *   spectrogram and a plausible-looking probability, so the FEATURES are what is
 *   gated here, tightly.
 *
 *   The probability is printed beside the Python one but deliberately NOT gated
 *   at the same tolerance, because the two do not agree and the reason is not a
 *   bug. Measured 2026-08-22 by feeding Python's own features through both
 *   runtimes: identical input, probabilities 0.441193 (onnxruntime, x86) versus
 *   0.421871 (onnxruntime-web, WASM) - while the same features through this
 *   extractor and the WASM runtime matched the Python-features-through-WASM
 *   result to 0.00e+0. The model is int8-quantized, and the two backends round
 *   their quantized kernels differently; the divergence is the runtime, not the
 *   chain. It matters for calibration (a threshold tuned on published numbers is
 *   a few points off in the browser) and not for correctness.
 *
 *   LATENCY - single-threaded WASM, which is the only mode available in the app
 *   (threads need `SharedArrayBuffer`, which needs COOP/COEP headers the
 *   Tailscale Serve path cannot send). A desktop reading here is the optimistic
 *   bound; the phone is the number that decides whether this ships, and only the
 *   lab page can take that one.
 *
 * The golden fixtures are generated by `scratchpad/golden.py` in the session that
 * added this, and are checked into `test/` for the unit test.
 */
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import * as ort from 'onnxruntime-web'

import { N_FRAMES, N_MELS, SMART_TURN_SAMPLE_RATE, WhisperFeatures } from '../src/smartTurnFeatures.ts'

const here = (relative: string) => fileURLToPath(new URL(relative, import.meta.url))

type Golden = {
  seconds: number
  probability: number
  mean: number
  std: number
  head: number[]
  stride37: number[]
}
const golden: Record<string, Golden> = JSON.parse(readFileSync(here('../test/smartTurnGolden.json'), 'utf8'))

/** Ported verbatim from `golden.py`; the LCG reproduces its noise exactly. */
function makeWaveform(samples: number): Float32Array {
  const out = new Float32Array(samples)
  let state = 1234567891
  for (let index = 0; index < samples; index++) {
    state = (state * 1664525 + 1013904223) % 4294967296
    const noise = 0.05 * ((state / 4294967296) * 2 - 1)
    const t = index / SMART_TURN_SAMPLE_RATE
    const sweep = Math.sin(2 * Math.PI * (120 + 900 * t) * t)
    const harmonic = 0.4 * Math.sin(2 * Math.PI * 1750 * t)
    const envelope = Math.min(1, t * 4) * Math.exp(-t / 2.5)
    out[index] = Math.fround((sweep + harmonic + noise) * envelope * 0.35)
  }
  return out
}

const median = (values: number[]) => [...values].sort((a, b) => a - b)[Math.floor(values.length / 2)]

ort.env.wasm.numThreads = 1
ort.env.wasm.proxy = false
ort.env.logLevel = 'error'

let weights: Uint8Array
try {
  weights = new Uint8Array(readFileSync(here('../models/smart-turn-v3.2-cpu.onnx')))
} catch {
  console.error('Smart Turn weights are missing. Run: uv run python tools/fetch_smart_turn.py')
  process.exit(1)
}

const loadStart = performance.now()
const session = await ort.InferenceSession.create(weights, {
  executionProviders: ['wasm'],
  interOpNumThreads: 1,
  intraOpNumThreads: 1,
  graphOptimizationLevel: 'all',
})
console.log(`weights ${(weights.byteLength / 1e6).toFixed(2)} MB, session ready in ${(performance.now() - loadStart).toFixed(0)} ms`)
console.log(`inputs ${session.inputNames.join(', ')} → outputs ${session.outputNames.join(', ')}\n`)

const extractor = new WhisperFeatures()
const tensor = new ort.Tensor('float32', new Float32Array(N_MELS * N_FRAMES), [1, N_MELS, N_FRAMES])

/** Tight: the features are ours to get right, and they fail silently. */
const FEATURE_TOLERANCE = 2e-3
/** Loose, and about the int8 backend gap documented above, not about this code. */
const PROBABILITY_TOLERANCE = 5e-2

let worstFeature = 0
let worstProbability = 0
const totals: number[] = []
for (const [label, expected] of Object.entries(golden)) {
  const audio = makeWaveform(Math.round(expected.seconds * SMART_TURN_SAMPLE_RATE))
  const featureTimes: number[] = []
  const inferTimes: number[] = []
  let probability = 0
  // Taken before the timing loop, and safe to hold across it only because the
  // loop recomputes into the very same reused buffer.
  const grid = extractor.compute(audio)
  for (let run = 0; run < 8; run++) {
    const featureStart = performance.now()
    extractor.compute(audio)
    featureTimes.push(performance.now() - featureStart)
    ;(tensor.data as Float32Array).set(grid)
    const inferStart = performance.now()
    const outputs = await session.run({ input_features: tensor })
    inferTimes.push(performance.now() - inferStart)
    probability = Number((outputs.logits.data as Float32Array)[0])
  }

  // Point samples, not just aggregates: a transposed grid has the same mean and
  // the same standard deviation as the correct one.
  let featureDelta = 0
  expected.head.forEach((value, index) => {
    featureDelta = Math.max(featureDelta, Math.abs(grid[index] - value))
  })
  expected.stride37.forEach((value, index) => {
    featureDelta = Math.max(featureDelta, Math.abs(grid[index * 37] - value))
  })
  worstFeature = Math.max(worstFeature, featureDelta)
  worstProbability = Math.max(worstProbability, Math.abs(probability - expected.probability))
  totals.push(median(featureTimes) + median(inferTimes))

  console.log(
    `${label.padEnd(9)} p=${probability.toFixed(6)}  python=${expected.probability.toFixed(6)}  `
    + `featureΔ=${featureDelta.toExponential(2)}  |  features ${median(featureTimes).toFixed(1)} ms, `
    + `infer ${median(inferTimes).toFixed(1)} ms (cold ${inferTimes[0].toFixed(1)} ms)`,
  )
}

console.log(
  `\nfeatures: worst delta ${worstFeature.toExponential(3)} (gate ${FEATURE_TOLERANCE})`
  + `\nprobability: worst delta ${worstProbability.toExponential(3)} vs Python - int8 backend gap, see the header`
  + `\nend-to-end: ${Math.min(...totals).toFixed(0)}-${Math.max(...totals).toFixed(0)} ms per utterance,`
  + ' single-threaded WASM, on THIS machine. The phone is the number that decides it;'
  + ' take that one in smart-turn-lab.html.',
)
if (worstFeature > FEATURE_TOLERANCE) {
  console.error('\nPARITY FAILED - the mel extractor disagrees with WhisperFeatureExtractor.')
  process.exit(1)
}
if (worstProbability > PROBABILITY_TOLERANCE) {
  console.error(
    '\nPARITY FAILED - the probability moved further than int8 backend variance explains.'
    + ' Suspect the weights file changed; re-run tools/fetch_smart_turn.py and re-check.',
  )
  process.exit(1)
}
