"""The old `mux.db` an upgrade has to survive, and the script that produced it.

Phase 11 ("migration compatibility"). `tests/test_migration_compatibility.py`
opens this fixture with today's store code and asserts the file is carried
forward rather than replaced; everything about *where the fixture came from*
lives here, because that provenance is the whole of its value.

Why it is generated by old code rather than written by hand
-----------------------------------------------------------
Every per-store migration test in this repository hand-writes the pre-migration
DDL it needs (`test_prompt_queue.py`, `test_voice.py`, `test_automation_phase6.py`,
`test_operational_telemetry_phase2.py`, `test_scheduled_resume.py`,
`test_prompt_queue_policy_migration.py`, `test_history_metadata.py`). That is the
right shape for one store's one column - the test states exactly the shape it is
migrating from, in the file that owns the migration - and it is the wrong shape
for "an install upgrades", because a hand-written whole-database schema is a
*claim* about what an old install looked like, written by the same person who
wrote the migration, and it drifts silently from the real thing.

So this fixture is not written. It is the `.dump` of a database created by
running the store constructors from a real revision of this repository
(`FIXTURE_REVISION`), extracted with `git archive` and imported on a clean
interpreter. The schema, the index set, and the recorded `schema_versions` rows
are that revision's own output, not an approximation of it - which is why
`schema_versions` in the fixture reads `automation=3`, `prompt_queue=2`,
`telemetry=3` rather than today's numbers.

It is deliberately never regenerated on a schedule. A fixture that tracks HEAD
tests nothing; this one gets older exactly the way a user's database does, and
the claim it protects ("a database written by the build of {FIXTURE_DATE} still
opens") stays true and stays meaningful. Regenerate it only to move the baseline
to a *newer* old revision, and only deliberately::

    uv run python tests/support/legacy_database.py --revision <sha>

The rows
--------
Synthesized per column from the fixture revision's own `PRAGMA table_info`,
rather than through that revision's store APIs. The point of a row here is only
that it is *there afterwards*, so binding the generator to a set of old method
signatures would buy nothing and would be the part that stopped working first.
`SEEDED_TABLES` names the tables that get one, chosen because a migration
touches them: a column add is cheap to survive, a table rebuild
(`automation_annotations`) is not, and the difference is invisible until data
that has to survive one is actually sitting in the file.
"""

from __future__ import annotations

import argparse
import json
import os
import sqlite3
import subprocess
import sys
import tarfile
import tempfile
from pathlib import Path

# The revision the committed fixture was generated from, recorded here rather
# than only in the fixture's header so a test can name it in a failure message.
FIXTURE_REVISION = "b45cbe8"
FIXTURE_DATE = "2026-08-01"

FIXTURE_PATH = Path(__file__).resolve().parents[1] / "fixtures" / "legacy_db" / "mux_db.sql"

# Stores that opened `mux.db` at the fixture revision, in the order `server.py`
# built them there. Ordering matters for exactly one reason: these stores share
# one file, and the first one to touch it is the one that creates
# `schema_versions`.
LEGACY_STORES = (
    ("swe_mux.history", "HistoryIndex", {}),
    ("swe_mux.operational_telemetry", "OperationalTelemetryStore", {}),
    ("swe_mux.tier0_store", "Tier0Store", {}),
    ("swe_mux.status_timeline", "StatusTimelineStore", {}),
    ("swe_mux.automation_store", "AutomationStore", {}),
    ("swe_mux.voice", "VoiceStore", {}),
    ("swe_mux.prompt_queue", "PromptQueueStore", {}),
    # `persist=False` is the default and skips the SQLite mirror entirely, so the
    # clipboard tables would be absent from a fixture built with it.
    ("swe_mux.clipboard_store", "ClipboardStore", {"persist": True}),
)

# One row each. Every one of these is a table some later migration alters; a
# table nothing migrates would prove nothing by surviving.
SEEDED_TABLES = (
    "history",
    "automation_annotations",
    "automation_budget_ledger",
    "automation_firings",
    "automation_observer_calls",
    "queue_messages",
    "quota_samples",
    "quota_reset_events",
    "process_evidence",
    "tier0_facts",
    "voice_clips",
    "clipboard_entries",
)

# A fixed instant rather than `time.time()`: a fixture whose bytes change on
# every regeneration hides which part of a diff was the schema.
SEEDED_AT = 1_754_000_000.0


def _synthesize(table: str, column: str, declared_type: str) -> object:
    """A value that satisfies the column's declared type and nothing more.

    Deliberately not realistic. A migration must not care what a row *says*, and
    a fixture full of plausible-looking data invites a reader to believe the test
    is asserting something about content when it is asserting survival.
    `*_json` is the one exception: those columns are read back as JSON by code a
    migration may call, and `'{}'` is the cheapest value that stays parseable.
    """
    kind = declared_type.upper()
    if column.endswith("_json"):
        return "{}"
    if "INT" in kind:
        return 1
    if "REAL" in kind or "FLOA" in kind or "DOUB" in kind:
        return SEEDED_AT
    if "BLOB" in kind:
        return b"legacy"
    return f"legacy-{table}-{column}"


def _seed_row(db: sqlite3.Connection, table: str) -> None:
    columns = [
        (str(row["name"]), str(row["type"]))
        for row in db.execute(f"PRAGMA table_info({table})").fetchall()
    ]
    if not columns:
        raise SystemExit(f"{table} does not exist at this revision; SEEDED_TABLES is stale")
    names = ", ".join(name for name, _ in columns)
    placeholders = ", ".join("?" for _ in columns)
    values = [_synthesize(table, name, kind) for name, kind in columns]
    db.execute(f"INSERT INTO {table}({names}) VALUES({placeholders})", values)


def emit(database: Path) -> None:
    """Run inside the *old* interpreter: build the schema, then seed it.

    Imported here rather than at module scope because this function is the only
    part of the file that runs against the fixture revision's `swe_mux`; the
    generator half below runs against the current one and must not import it.
    """
    import importlib

    database.parent.mkdir(parents=True, exist_ok=True)
    for module_name, class_name, kwargs in LEGACY_STORES:
        store = getattr(importlib.import_module(module_name), class_name)(database, **kwargs)
        close = getattr(store, "close", None)
        if close is not None:
            close()

    db = sqlite3.connect(database)
    db.row_factory = sqlite3.Row
    for table in SEEDED_TABLES:
        _seed_row(db, table)
    db.commit()
    db.close()


def _extract_revision(revision: str, destination: Path) -> None:
    """`git archive` rather than a worktree: it registers nothing and locks nothing."""
    archive = destination / "src.tar"
    with archive.open("wb") as handle:
        subprocess.run(  # noqa: S603 - fixed argv
            ["git", "archive", revision, "src/swe_mux"],  # noqa: S607 - git from PATH
            check=True,
            stdout=handle,
        )
    with tarfile.open(archive) as tar:
        tar.extractall(destination, filter="data")


def _dump(database: Path, revision: str, resolved: str) -> str:
    db = sqlite3.connect(database)
    versions = {
        str(row[0]): int(row[1])
        for row in db.execute("SELECT store, version FROM schema_versions").fetchall()
    }
    body = "\n".join(db.iterdump())
    db.close()
    header = [
        "-- Generated. Do not edit; see tests/support/legacy_database.py.",
        "--",
        f"-- `sqlite3 .dump` of a mux.db created by the store code at {revision}",
        f"-- ({resolved}) - what an install from that build actually had on disk,",
        "-- rather than a reconstruction of it. Regenerate only to move the",
        "-- baseline forward; the schema versions it recorded then were:",
        f"--   {json.dumps(versions, sort_keys=True)}",
        "",
    ]
    return "\n".join(header) + body + "\n"


def regenerate(revision: str, output: Path) -> None:
    resolved = subprocess.run(  # noqa: S603 - fixed argv
        ["git", "rev-parse", revision],  # noqa: S607 - git from PATH
        check=True,
        capture_output=True,
        text=True,
    ).stdout.strip()
    with tempfile.TemporaryDirectory(prefix="swe-mux-legacy-db-") as raw:
        workdir = Path(raw)
        _extract_revision(revision, workdir)
        database = workdir / "data" / "mux.db"
        # `-P` keeps the script's own directory off `sys.path`, so `swe_mux`
        # resolves to the extracted revision and can never resolve to this
        # checkout - the fixture would silently become a copy of HEAD's schema.
        subprocess.run(  # noqa: S603 - fixed argv
            [sys.executable, "-P", str(Path(__file__).resolve()), "--emit-into", str(database)],
            check=True,
            cwd=workdir,
            env=_inherited() | {"PYTHONPATH": str(workdir / "src")},
        )
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(_dump(database, revision, resolved), encoding="utf-8", newline="\n")
        print(f"wrote {output} ({output.stat().st_size} bytes) from {revision} ({resolved})")


def _inherited() -> dict[str, str]:
    """The environment variables a Python child needs on Windows, and no more."""
    return {
        key: value
        for key, value in os.environ.items()
        # `USERPROFILE`/`HOME` are not optional: `config.py` resolves its default
        # `data_dir` off `Path.home()` at class-definition time, so importing any
        # store without one raises before a single table is created.
        if key
        in {
            "PATH",
            "SYSTEMROOT",
            "TEMP",
            "TMP",
            "APPDATA",
            "LOCALAPPDATA",
            "HOME",
            "USERPROFILE",
            "HOMEDRIVE",
            "HOMEPATH",
        }
    }


def load_legacy_database(destination: Path) -> Path:
    """Materialize the committed fixture as a real database file at `destination`."""
    destination.parent.mkdir(parents=True, exist_ok=True)
    db = sqlite3.connect(destination)
    try:
        db.executescript(FIXTURE_PATH.read_text(encoding="utf-8"))
        db.commit()
    finally:
        db.close()
    return destination


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--revision", default=FIXTURE_REVISION)
    parser.add_argument("--output", type=Path, default=FIXTURE_PATH)
    parser.add_argument("--emit-into", type=Path, help=argparse.SUPPRESS)
    args = parser.parse_args(argv)
    if args.emit_into is not None:
        emit(args.emit_into)
        return 0
    regenerate(args.revision, args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
