import { useEffect, useRef, useState } from 'preact/hooks'
import { api } from './api'
import { useModalFocus } from './modalFocus'

type Rule={id:string;name:string;enabled:boolean;shadow:boolean;trigger:string;revision:string;source:string}
type Firing={id:string;event_seq:number;event_type:string;rule_id:string;status:string;shadow:number;created_at:number;error?:string;condition_trace:Array<{field:string;matched:boolean;actual:unknown;expected:unknown}>}
type ActionResult={id:string;firing_id:string;action_index:number;kind:string;status:string;detail:unknown;error?:string;created_at:number}
type ObserverCall={id:string;firing_id:string;rule_id:string;status:string;requested_model?:string;resolved_model?:string;input_bytes:number;input_tokens:number;output_tokens:number;cost_usd?:number;latency_ms?:number;error?:string;created_at:number}
type Annotation={id:string;agent_run_id:string;session_id?:string;tag:string;content:string;provenance:string;requested_model?:string;resolved_model?:string;input_tokens:number;output_tokens:number;cost_usd?:number;confidence?:number;created_at:number}
type InboxItem={id:string;session_id?:string;kind:string;title:string;message:string;severity:string;evidence:Array<{signal:string;value:unknown}>;read_at?:number;created_at:number}
type AutomationData={
  engine:{enabled:boolean;diagnostic?:string;rules:Rule[];queue:{size:number;capacity:number;dropped:number;loop_rejections:number};capabilities:{triggers:string[];observer_schemas:string[]}}
  provider:{secret:{configured:boolean;source:string};models:{models:unknown[];stale:boolean;error?:string};cheap_model:string;standard_model:string}
  spend_today:{tokens:number;cost_usd:number};observer_calls:Record<string,number>;annotations:Record<string,number>;unread_notifications:number
  recent_firings:Firing[];recent_action_results:ActionResult[];recent_observer_calls:ObserverCall[];recent_annotations:Annotation[]
}
type Telemetry={since:number;dimensions:Array<{backend:string;model:string;runs:number;ended_runs:number;average_duration_s?:number;tokens_in:number;tokens_out:number;average_final_context_pct?:number;average_peak_context_pct?:number;turns_per_run:number;stalls_per_run:number;approvals_per_run:number;completion_evidence_count:number;completion_evidence_runs:number}>;event_counts:Record<string,number>;interpretation:string;observer_spend:{tokens:number;cost_usd:number};provider_cost_dimensions:Array<{backend:string;model:string;tokens:number;cost_usd:number;cost_is_estimate:boolean;attribution:string}>;cost_note:string}
type Experience={id:string;backend:string;error_summary:string;resolution_summary:string;source_run_id:string;confidence?:number;created_at:number}
type InjectionSafety={research_only:boolean;authorizes_actuation:boolean;sessions:Array<{session_id:string;backend:string;state:string;candidate_safe:boolean;authorized:boolean;diagnostic:string}>}
type EndedRun={id:string;backend:string;name:string;generated_title?:string;auto_named?:number;cwd:string;spawned_at:number;exited_at?:number;transcript_path?:string;project_label?:string}
type ObserverBatch={id:string;kind:string;status:string;run_ids:string[];preview:unknown[];calls:number;tokens:number;cost_usd:number;error?:string;created_at:number;completed_at?:number}

const money=new Intl.NumberFormat(undefined,{style:'currency',currency:'USD',maximumFractionDigits:4})
const integer=new Intl.NumberFormat()

export function AutomationDashboard({onClose,onConfigure,onOpenSession}:{onClose:()=>void;onConfigure:()=>void;onOpenSession:(id:string)=>void}){
  const [data,setData]=useState<AutomationData|null>(null)
  const [inbox,setInbox]=useState<InboxItem[]>([])
  const [telemetry,setTelemetry]=useState<Telemetry|null>(null)
  const [experiences,setExperiences]=useState<Experience[]>([])
  const [injectionSafety,setInjectionSafety]=useState<InjectionSafety|null>(null)
  const [view,setView]=useState<'overview'|'rules'|'annotations'|'inbox'|'fleet'|'experience'>('overview')
  const [message,setMessage]=useState('Loading automation state…')
  const [error,setError]=useState('')
  const [eventSeq,setEventSeq]=useState('')
  const [dryRun,setDryRun]=useState<unknown>(null)
  const [batchKind,setBatchKind]=useState('experience')
  const [batchRuns,setBatchRuns]=useState<Set<string>>(new Set())
  const [batchCandidates,setBatchCandidates]=useState<EndedRun[]>([])
  const [batches,setBatches]=useState<ObserverBatch[]>([])
  const [batchPreview,setBatchPreview]=useState<Record<string,unknown>|null>(null)
  const panel=useRef<HTMLElement>(null)
  useModalFocus(panel,onClose)

  const load=async()=>{
    try{
      const [dashboard,notifications,workloads,experience,injection,history,batchHistory]=await Promise.all([
        api<AutomationData>('GET','/api/automation/dashboard'),
        api<{items:InboxItem[]}>('GET','/api/automation/notifications'),
        api<Telemetry>('GET','/api/telemetry/workloads'),
        api<{items:Experience[]}>('GET','/api/experiences'),
        api<InjectionSafety>('GET','/api/automation/injection-safety'),
        api<{items:EndedRun[]}>('GET','/api/history?limit=100'),
        api<{items:ObserverBatch[]}>('GET','/api/automation/batches'),
      ])
      setData(dashboard);setInbox(notifications.items);setTelemetry(workloads);setExperiences(experience.items);setInjectionSafety(injection);setBatchCandidates(history.items.filter(item=>Boolean(item.exited_at&&item.transcript_path)));setBatches(batchHistory.items)
      setMessage(`ready · ${dashboard.engine.rules.length} canonical rules · ${dashboard.unread_notifications} unread`);setError('')
    }catch(cause){setError(cause instanceof Error?cause.message:String(cause))}
  }
  useEffect(()=>{void load()},[])

  const runDry=async()=>{try{setDryRun(null);setMessage('Evaluating selected historical event with side effects disabled…');const result=await api('POST','/api/automation/dry-run',{event_seq:Number(eventSeq)});setDryRun(result);setMessage('Dry-run complete. No actions or model calls were executed.')}catch(cause){setError(cause instanceof Error?cause.message:String(cause))}}
  const markRead=async(item:InboxItem)=>{await api('PATCH',`/api/automation/notifications/${item.id}`,{read:!item.read_at});await load()}
  const updateRule=async(rule:Rule,change:Partial<Pick<Rule,'enabled'|'shadow'>>)=>{try{setMessage(`Updating ${rule.name}…`);await api('PATCH',`/api/automation/rules/${encodeURIComponent(rule.id)}`,change);await load()}catch(cause){setError(cause instanceof Error?cause.message:String(cause))}}
  const previewBatch=async(confirm=false)=>{try{const run_ids=Array.from(batchRuns);const result=await api<Record<string,unknown>>('POST','/api/automation/batches',{kind:batchKind,run_ids,confirm,...(confirm?{preview_token:String(batchPreview?.preview_token||'')}:{})});setBatchPreview(result);setMessage(confirm?'Batch started. Results remain preview/export-only.':'Batch estimate ready; review before starting.');if(confirm)await load()}catch(cause){setError(cause instanceof Error?cause.message:String(cause))}}
  const toggleBatchRun=(id:string)=>{setBatchPreview(null);setBatchRuns(current=>{const next=new Set(current);if(next.has(id))next.delete(id);else if(next.size<25)next.add(id);return next})}

  return <div class="usage-layer automation-layer" role="dialog" aria-modal="true" aria-label="Automation" onMouseDown={event=>event.target===event.currentTarget&&onClose()}>
    <section class="usage-panel automation-panel" ref={panel}>
      <header><div><span>AUTOMATION::CONTROL PLANE</span><strong>Universal hooks · read-only observers · fleet intelligence</strong></div><div class="usage-header-actions"><button onClick={onConfigure}>configure</button><button aria-label="Close automation" onClick={onClose}>×</button></div></header>
      <div class="usage-actions automation-tabs" role="tablist">{(['overview','rules','annotations','inbox','fleet','experience'] as const).map(item=><button role="tab" aria-selected={view===item} class={view===item?'active':''} onClick={()=>setView(item)}>{item}{item==='inbox'&&data?.unread_notifications?` [${data.unread_notifications}]`:''}</button>)}</div>
      <div class={`usage-progress ${!data&&!error?'running':''}`} role="status" aria-live="polite"><span>{error?'!':data?'·':'◌'}</span><strong>{error||message}</strong></div>
      <main>
        {view==='overview'&&<><div class="usage-summary"><article><span>automation</span><strong>{data?.engine.enabled?'on':'off'}</strong></article><article><span>provider</span><strong>{data?.provider.secret.configured?'ready':'no key'}</strong></article><article><span>calls today</span><strong>{integer.format(Object.values(data?.observer_calls||{}).reduce((a,b)=>a+b,0))}</strong></article><article><span>tokens today</span><strong>{integer.format(data?.spend_today.tokens||0)}</strong></article><article><span>cost today</span><strong>{money.format(data?.spend_today.cost_usd||0)}</strong></article><article><span>queue</span><strong>{data?.engine.queue.size||0}/{data?.engine.queue.capacity||0}</strong></article></div>
          <section class="usage-table"><h3>Provider + safety</h3><p>OpenRouter key::{data?.provider.secret.source||'none'} · cheap::{data?.provider.cheap_model||'unset'} · standard::{data?.provider.standard_model||'unset'}</p><p>Observer results can annotate and notify only. PTY writes, approvals, arbitrary HTTP, workers, repository rules, and model-directed actions are unavailable.</p><p>queue dropped::{data?.engine.queue.dropped||0} · chain loops rejected::{data?.engine.queue.loop_rejections||0}</p>{data?.engine.diagnostic&&<p class="usage-error">{data.engine.diagnostic}</p>}</section>
          <section class="usage-table"><h3>Historical event dry-run</h3><p>Evaluate canonical rules against one persisted event. No firing, action, checkpoint, model call, or spend record is written.</p><div class="automation-inline"><input type="number" placeholder="event sequence" value={eventSeq} onInput={event=>setEventSeq(event.currentTarget.value)}/><button disabled={!eventSeq} onClick={()=>void runDry()}>dry-run</button></div>{dryRun&&<pre>{JSON.stringify(dryRun,null,2)}</pre>}</section></>}
        {view==='rules'&&<div class="usage-tables"><section class="usage-table"><h3>Canonical rules</h3>{data?.engine.rules.length?data.engine.rules.map(rule=><article class="automation-row"><span class={`state-dot ${rule.enabled?'idle':'running'}`}/><div><strong>{rule.name}</strong><small>{rule.id} · on::{rule.trigger} · {rule.shadow?'shadow':'live'}</small><em>revision::{rule.revision} · source::{rule.source}</em></div><div class="automation-row-actions"><button onClick={()=>void updateRule(rule,{enabled:!rule.enabled})}>{rule.enabled?'disable':'enable'}</button><button onClick={()=>void updateRule(rule,{shadow:!rule.shadow})}>{rule.shadow?'make live':'shadow'}</button></div></article>):<p>No canonical rules. Built-in observers are controlled in Settings.</p>}</section><section class="usage-table"><h3>Recent firings</h3>{data?.recent_firings.map(firing=><details><summary>{firing.rule_id} · {firing.status} · event::{firing.event_seq}</summary><small>{new Date(firing.created_at*1000).toLocaleString()} · trigger::{firing.event_type}{firing.shadow?' · shadow':''}</small>{firing.error&&<p>{firing.error}</p>}<pre>{JSON.stringify(firing.condition_trace,null,2)}</pre></details>)}</section><section class="usage-table"><h3>Action results</h3>{data?.recent_action_results.map(item=><details><summary>{item.kind} · {item.status} · action::{item.action_index}</summary><small>firing::{item.firing_id} · {new Date(item.created_at*1000).toLocaleString()}</small>{item.error&&<p>{item.error}</p>}<pre>{JSON.stringify(item.detail,null,2)}</pre></details>)}</section><section class="usage-table"><h3>Observer calls</h3>{data?.recent_observer_calls.map(item=><details><summary>{item.rule_id} · {item.status} · {item.resolved_model||item.requested_model||'model unavailable'}</summary><small>{item.input_tokens+item.output_tokens} tokens · {money.format(item.cost_usd||0)} · {item.latency_ms??'—'}ms · input::{item.input_bytes} bytes</small>{item.error&&<p>{item.error}</p>}</details>)}</section></div>}
        {view==='annotations'&&<section class="usage-table"><h3>Derived annotations</h3>{data?.recent_annotations.length?data.recent_annotations.map(item=><article class="automation-row"><span class="state-dot idle"/><div><strong>{item.tag} · {item.content}</strong><small>{new Date(item.created_at*1000).toLocaleString()} · run::{item.agent_run_id}</small><em>{item.provenance} · model::{item.resolved_model||'deterministic'} · confidence::{item.confidence??'—'} · cost::{money.format(item.cost_usd||0)}</em></div>{item.session_id&&<button onClick={()=>onOpenSession(item.session_id!)}>session</button>}</article>):<p>No observer annotations yet.</p>}</section>}
        {view==='inbox'&&<section class="usage-table"><h3>Attention inbox</h3>{inbox.length?inbox.map(item=><article class={`automation-row ${item.read_at?'read':''}`}><span class={`state-dot ${item.severity==='warning'?'awaiting':'idle'}`}/><div><strong>{item.title}</strong><span>{item.message}</span><small>{new Date(item.created_at*1000).toLocaleString()} · {item.kind} · {item.severity}</small>{item.evidence.length>0&&<details><summary>evidence</summary><pre>{JSON.stringify(item.evidence,null,2)}</pre></details>}</div>{item.session_id&&<button onClick={()=>onOpenSession(item.session_id!)}>session</button>}<button onClick={()=>void markRead(item)}>{item.read_at?'unread':'read'}</button></article>):<p>No attention records.</p>}</section>}
        {view==='fleet'&&<><section class="usage-table"><h3>Observed workload telemetry</h3><p>Correlation only; this is not a causal benchmark.</p><div class="usage-table-scroll"><table><thead><tr><th>backend/model</th><th>runs</th><th>ended</th><th>avg duration</th><th>turns/run</th><th>stalls/run</th><th>approvals/run</th><th>context final/peak</th><th>completion evidence</th><th>tokens</th></tr></thead><tbody>{telemetry?.dimensions.map(row=><tr><td>{row.backend} / {row.model}</td><td>{row.runs}</td><td>{row.ended_runs}</td><td>{Math.round(row.average_duration_s||0)}s</td><td>{row.turns_per_run.toFixed(1)}</td><td>{row.stalls_per_run.toFixed(2)}</td><td>{row.approvals_per_run.toFixed(2)}</td><td>{Math.round((row.average_final_context_pct||0)*100)}% / {Math.round((row.average_peak_context_pct||0)*100)}%</td><td>{row.completion_evidence_runs}/{row.runs} runs · {row.completion_evidence_count} signals</td><td>{integer.format((row.tokens_in||0)+(row.tokens_out||0))}</td></tr>)}</tbody></table></div><pre>{JSON.stringify(telemetry?.event_counts||{},null,2)}</pre>{telemetry?.provider_cost_dimensions.length?<><h3>Provider/model cost aggregates</h3><p>{telemetry.cost_note}</p><div class="usage-table-scroll"><table><thead><tr><th>backend/model</th><th>tokens</th><th>cost</th><th>source</th></tr></thead><tbody>{telemetry.provider_cost_dimensions.map(row=><tr><td>{row.backend} / {row.model}</td><td>{integer.format(row.tokens)}</td><td>{money.format(row.cost_usd)}{row.cost_is_estimate?' est.':''}</td><td>{row.attribution}</td></tr>)}</tbody></table></div></>:null}</section><section class="usage-table"><h3>Absence report</h3><p>Attention inbox items and annotations are aggregated since your last terminal attach/input activity.</p><button onClick={async()=>{const report=await api('GET','/api/attention/absence');setDryRun(report);setMessage('Absence report refreshed.')}}>generate report</button>{dryRun&&<pre>{JSON.stringify(dryRun,null,2)}</pre>}</section><section class="usage-table"><h3>Future injection gate diagnostics</h3><p>Research only · actuation authorized::{injectionSafety?.authorizes_actuation?'yes':'no'}. Unknown composer, terminal-mode, or adapter etiquette evidence always keeps the gate closed.</p>{injectionSafety?.sessions.map(item=><article class="automation-row"><span class="state-dot running"/><div><strong>{item.backend} · {item.session_id}</strong><small>state::{item.state} · candidate::{item.candidate_safe?'yes':'no'} · authorized::no</small><em>{item.diagnostic}</em></div></article>)}</section></>}
        {view==='experience'&&<><section class="usage-table"><h3>Experience index</h3><p>Prior error → resolution findings are suggestions only and are never injected into an agent.</p>{experiences.map(item=><article class="automation-row"><span class="state-dot idle"/><div><strong>{item.error_summary}</strong><span>{item.resolution_summary}</span><small>{item.backend} · run::{item.source_run_id} · confidence::{item.confidence??'—'}</small></div></article>)}</section><section class="usage-table"><h3>Explicit batch observer</h3><p>Select up to 25 ended agent runs. A confirmed batch reads only their bounded transcripts and produces preview/export data; it never mutates a repository.</p><label>kind<select value={batchKind} onChange={event=>{setBatchKind(event.currentTarget.value);setBatchPreview(null)}}><option value="experience">error → resolution</option><option value="procedure">procedures</option><option value="doc-drift">doc drift</option><option value="convention">conventions</option><option value="regression">regression candidates</option></select></label><div class="batch-run-picker">{batchCandidates.length?batchCandidates.map(run=><label><input type="checkbox" checked={batchRuns.has(run.id)} disabled={!batchRuns.has(run.id)&&batchRuns.size>=25} onChange={()=>toggleBatchRun(run.id)}/><span><strong>[{run.backend}] {run.auto_named!==0&&run.generated_title?run.generated_title:run.name}</strong><small>{run.project_label||'Ungrouped'} · {new Date(run.spawned_at*1000).toLocaleString()}</small></span></label>):<p>No ended agent transcripts are available.</p>}</div><div class="automation-inline"><span>{batchRuns.size}/25 selected</span><button disabled={!batchRuns.size} onClick={()=>void previewBatch(false)}>estimate</button><button class="primary" disabled={!batchPreview||!batchRuns.size} onClick={()=>void previewBatch(true)}>start reviewed batch</button></div>{batchPreview&&<pre>{JSON.stringify(batchPreview,null,2)}</pre>}</section><section class="usage-table"><h3>Recent observer batches</h3>{batches.length?batches.map(batch=><details><summary>{batch.kind} · {batch.status} · {batch.run_ids.length} runs</summary><small>{new Date(batch.created_at*1000).toLocaleString()} · {batch.calls} calls · {integer.format(batch.tokens)} tokens · {money.format(batch.cost_usd)}</small>{batch.error&&<p class="usage-error">{batch.error}</p>}<pre>{JSON.stringify(batch.preview,null,2)}</pre></details>):<p>No reviewed batches have run.</p>}</section></>}
      </main>
      <footer><span>Out-of-band · bounded · budgeted · no agent actuation</span><button onClick={()=>void load()}>refresh</button></footer>
    </section>
  </div>
}
