/**
 * Whisper log-mel features, in the browser, for the Smart Turn v3 turn detector.
 *
 * The ONNX model does NOT take audio. Its one input is `input_features`, an
 * (80, 800) log-mel spectrogram produced by HuggingFace's
 * `WhisperFeatureExtractor(chunk_length=8)` - so the whole preprocessing chain
 * has to exist here before a single probability can be computed, and any silent
 * disagreement with the Python reference shows up as a plausible-looking number
 * rather than as an error. `test/smartTurnFeatures.test.ts` pins every stage
 * against a golden vector generated by the real extractor.
 *
 * The chain, in the order `inference.py` runs it:
 *
 *   1. truncate to the LAST 8 s, or zero-pad at the FRONT to reach 8 s
 *   2. zero-mean unit-variance normalize the whole 128000-sample vector
 *   3. reflect-pad 200 samples each side, frame at 400/160, periodic Hann
 *   4. 400-point real FFT, power spectrum, 201 bins
 *   5. 80 Slaney-normalized mel filters over 0-8000 Hz
 *   6. log10, floored 8 dB below the maximum, rescaled to roughly [-1, 1]
 *   7. drop the last frame, leaving exactly 800
 *
 * Step 4 is the only awkward one: 400 is not a power of two, and a naive DFT
 * would cost ~64M operations per inference. Bluestein's algorithm turns it into
 * three 1024-point radix-2 transforms, which is what makes this viable at all.
 */

/** Smart Turn v3 is trained on exactly this much context, at this rate. */
export const SMART_TURN_SAMPLE_RATE = 16_000
export const SMART_TURN_WINDOW_SECONDS = 8
export const SMART_TURN_SAMPLES = SMART_TURN_SAMPLE_RATE * SMART_TURN_WINDOW_SECONDS

/** Whisper's fixed feature geometry. None of these are tunable. */
export const N_FFT = 400
export const HOP_LENGTH = 160
export const N_MELS = 80
export const N_FREQS = N_FFT / 2 + 1
/** 128000 / 160, after the last frame is dropped the way Whisper drops it. */
export const N_FRAMES = SMART_TURN_SAMPLES / HOP_LENGTH

/** Slaney mel scale, as used by `mel_filter_bank(..., mel_scale="slaney")`. */
const MIN_LOG_HERTZ = 1000
const MIN_LOG_MEL = 15
const LOGSTEP = 27 / Math.log(6.4)

function hertzToMel(hertz: number): number {
  if (hertz < MIN_LOG_HERTZ) return (3 * hertz) / 200
  return MIN_LOG_MEL + Math.log(hertz / MIN_LOG_HERTZ) * LOGSTEP
}

function melToHertz(mel: number): number {
  if (mel < MIN_LOG_MEL) return (200 * mel) / 3
  return MIN_LOG_HERTZ * Math.exp((mel - MIN_LOG_MEL) / LOGSTEP)
}

/**
 * The (201 x 80) triangular filterbank, Slaney-normalized.
 *
 * Stored transposed relative to numpy's `mel_filters` because the only thing it
 * is ever used for is `filters.T @ power`, and iterating mel-major turns that
 * into one contiguous sweep per mel bin.
 */
function melFilterBank(): Float64Array[] {
  const fftFreqs = new Float64Array(N_FREQS)
  for (let index = 0; index < N_FREQS; index++) {
    fftFreqs[index] = (index * SMART_TURN_SAMPLE_RATE) / 2 / (N_FREQS - 1)
  }
  const melMin = hertzToMel(0)
  const melMax = hertzToMel(SMART_TURN_SAMPLE_RATE / 2)
  const filterFreqs = new Float64Array(N_MELS + 2)
  for (let index = 0; index < N_MELS + 2; index++) {
    filterFreqs[index] = melToHertz(melMin + ((melMax - melMin) * index) / (N_MELS + 1))
  }
  const bank: Float64Array[] = []
  for (let mel = 0; mel < N_MELS; mel++) {
    const row = new Float64Array(N_FREQS)
    const left = filterFreqs[mel]
    const center = filterFreqs[mel + 1]
    const right = filterFreqs[mel + 2]
    // Slaney normalization: each filter integrates to a constant area, which is
    // what keeps low mel bins from dominating the log spectrogram.
    const enorm = 2 / (right - left)
    for (let bin = 0; bin < N_FREQS; bin++) {
      const frequency = fftFreqs[bin]
      const down = (frequency - left) / (center - left)
      const up = (right - frequency) / (right - center)
      const value = Math.max(0, Math.min(down, up))
      row[bin] = value * enorm
    }
    bank.push(row)
  }
  return bank
}

/** Periodic Hann, matching `window_function(400, "hann", periodic=True)`. */
function hannWindow(): Float64Array {
  const window = new Float64Array(N_FFT)
  for (let index = 0; index < N_FFT; index++) {
    window[index] = 0.5 * (1 - Math.cos((2 * Math.PI * index) / N_FFT))
  }
  return window
}

/** In-place iterative radix-2 FFT. `inverse` skips the 1/n scaling. */
function fftRadix2(real: Float64Array, imag: Float64Array, inverse: boolean): void {
  const size = real.length
  for (let i = 1, j = 0; i < size; i++) {
    let bit = size >> 1
    for (; j & bit; bit >>= 1) j ^= bit
    j ^= bit
    if (i < j) {
      let swap = real[i]; real[i] = real[j]; real[j] = swap
      swap = imag[i]; imag[i] = imag[j]; imag[j] = swap
    }
  }
  for (let length = 2; length <= size; length <<= 1) {
    const angle = ((inverse ? 2 : -2) * Math.PI) / length
    const stepReal = Math.cos(angle)
    const stepImag = Math.sin(angle)
    for (let start = 0; start < size; start += length) {
      let wReal = 1
      let wImag = 0
      for (let offset = 0; offset < length / 2; offset++) {
        const a = start + offset
        const b = a + length / 2
        const tReal = real[b] * wReal - imag[b] * wImag
        const tImag = real[b] * wImag + imag[b] * wReal
        real[b] = real[a] - tReal
        imag[b] = imag[a] - tImag
        real[a] += tReal
        imag[a] += tImag
        const nextReal = wReal * stepReal - wImag * stepImag
        wImag = wReal * stepImag + wImag * stepReal
        wReal = nextReal
      }
    }
  }
}

/**
 * A 400-point DFT via Bluestein's chirp-z transform.
 *
 * Only the first 201 bins are ever read, but the whole transform is computed -
 * Bluestein does not offer a real-input shortcut, and at 1024 points three times
 * per frame it is still two orders of magnitude cheaper than the direct sum.
 */
class Bluestein {
  private readonly size = N_FFT
  private readonly padded: number
  private readonly chirpReal: Float64Array
  private readonly chirpImag: Float64Array
  private readonly kernelReal: Float64Array
  private readonly kernelImag: Float64Array
  private readonly aReal: Float64Array
  private readonly aImag: Float64Array

  constructor() {
    let padded = 1
    while (padded < 2 * this.size - 1) padded <<= 1
    this.padded = padded
    this.chirpReal = new Float64Array(this.size)
    this.chirpImag = new Float64Array(this.size)
    for (let index = 0; index < this.size; index++) {
      // exp(-i*pi*index^2/size), with the exponent reduced mod 2*size before the
      // trig call: index^2 reaches 159201 here, and passing that straight to
      // Math.cos loses low-order bits to argument reduction.
      const angle = (-Math.PI * ((index * index) % (2 * this.size))) / this.size
      this.chirpReal[index] = Math.cos(angle)
      this.chirpImag[index] = Math.sin(angle)
    }
    const kernelReal = new Float64Array(padded)
    const kernelImag = new Float64Array(padded)
    kernelReal[0] = this.chirpReal[0]
    kernelImag[0] = -this.chirpImag[0]
    for (let index = 1; index < this.size; index++) {
      kernelReal[index] = this.chirpReal[index]
      kernelImag[index] = -this.chirpImag[index]
      kernelReal[padded - index] = this.chirpReal[index]
      kernelImag[padded - index] = -this.chirpImag[index]
    }
    fftRadix2(kernelReal, kernelImag, false)
    this.kernelReal = kernelReal
    this.kernelImag = kernelImag
    this.aReal = new Float64Array(padded)
    this.aImag = new Float64Array(padded)
  }

  /** Power spectrum |X[k]|^2 for k in [0, 201), written into `out`. */
  power(frame: Float64Array, out: Float64Array): void {
    const { aReal, aImag, padded } = this
    aReal.fill(0)
    aImag.fill(0)
    for (let index = 0; index < this.size; index++) {
      aReal[index] = frame[index] * this.chirpReal[index]
      aImag[index] = frame[index] * this.chirpImag[index]
    }
    fftRadix2(aReal, aImag, false)
    for (let index = 0; index < padded; index++) {
      const real = aReal[index] * this.kernelReal[index] - aImag[index] * this.kernelImag[index]
      const imag = aReal[index] * this.kernelImag[index] + aImag[index] * this.kernelReal[index]
      aReal[index] = real
      aImag[index] = imag
    }
    fftRadix2(aReal, aImag, true)
    for (let bin = 0; bin < N_FREQS; bin++) {
      // The inverse transform above is unscaled, so the 1/padded lands here.
      const real = (aReal[bin] * this.chirpReal[bin] - aImag[bin] * this.chirpImag[bin]) / padded
      const imag = (aReal[bin] * this.chirpImag[bin] + aImag[bin] * this.chirpReal[bin]) / padded
      out[bin] = real * real + imag * imag
    }
  }
}

/**
 * Truncate to the last 8 seconds, or zero-pad at the FRONT to reach them.
 *
 * Front-padding is not cosmetic: the model is trained with the speech flush
 * against the end of the window, because the end is where the turn boundary it
 * is judging lives. Padding the other side moves the boundary into the middle of
 * the input and the probabilities become noise.
 */
export function fitWindow(audio: Float32Array): Float32Array {
  if (audio.length === SMART_TURN_SAMPLES) return audio
  if (audio.length > SMART_TURN_SAMPLES) return audio.subarray(audio.length - SMART_TURN_SAMPLES)
  const fitted = new Float32Array(SMART_TURN_SAMPLES)
  fitted.set(audio, SMART_TURN_SAMPLES - audio.length)
  return fitted
}

/**
 * The extractor. Built once and reused: the filterbank and the Bluestein tables
 * cost more to construct than one inference costs to run.
 */
export class WhisperFeatures {
  private readonly window = hannWindow()
  private readonly bank = melFilterBank()
  private readonly fft = new Bluestein()
  private readonly frame = new Float64Array(N_FFT)
  private readonly power = new Float64Array(N_FREQS)
  /** (80, 800) row-major, matching the numpy array the ONNX graph expects. */
  private readonly out = new Float32Array(N_MELS * N_FRAMES)
  private readonly padded = new Float64Array(SMART_TURN_SAMPLES + N_FFT)

  /**
   * One log-mel spectrogram, reusing the same output buffer every call.
   *
   * The caller must copy it if it needs to outlive the next call - the reuse is
   * deliberate, because allocating 256 KB per frame of audio is exactly the kind
   * of churn that makes a latency measurement measure the garbage collector.
   */
  compute(audio: Float32Array): Float32Array {
    const fitted = fitWindow(audio)

    // Zero-mean unit-variance over the whole window, including any front
    // padding, which is what `do_normalize=True` does once the audio has already
    // been padded to max_length.
    let sum = 0
    for (let index = 0; index < fitted.length; index++) sum += fitted[index]
    const mean = sum / fitted.length
    let variance = 0
    for (let index = 0; index < fitted.length; index++) {
      const centered = fitted[index] - mean
      variance += centered * centered
    }
    variance /= fitted.length
    const scale = 1 / Math.sqrt(variance + 1e-7)

    // Reflect padding of n_fft/2 on both sides, so frame k is centred on sample
    // k*hop. `np.pad(mode="reflect")` does not repeat the edge sample.
    const half = N_FFT / 2
    const { padded } = this
    for (let index = 0; index < SMART_TURN_SAMPLES; index++) {
      padded[half + index] = (fitted[index] - mean) * scale
    }
    for (let index = 0; index < half; index++) {
      padded[half - 1 - index] = padded[half + 1 + index]
      padded[half + SMART_TURN_SAMPLES + index] = padded[half + SMART_TURN_SAMPLES - 2 - index]
    }

    // Whisper computes 801 frames from this and throws the last one away, so it
    // is simply never computed here.
    let maximum = -Infinity
    for (let frameIndex = 0; frameIndex < N_FRAMES; frameIndex++) {
      const start = frameIndex * HOP_LENGTH
      for (let index = 0; index < N_FFT; index++) {
        this.frame[index] = padded[start + index] * this.window[index]
      }
      this.fft.power(this.frame, this.power)
      for (let mel = 0; mel < N_MELS; mel++) {
        const row = this.bank[mel]
        let energy = 0
        for (let bin = 0; bin < N_FREQS; bin++) energy += row[bin] * this.power[bin]
        const value = Math.log10(Math.max(energy, 1e-10))
        this.out[mel * N_FRAMES + frameIndex] = value
        if (value > maximum) maximum = value
      }
    }

    // Dynamic range floored 8 dB below the loudest bin, then rescaled. The floor
    // is what stops digital silence from turning into a -100 dB cliff that
    // dominates the model's input.
    const floor = maximum - 8
    for (let index = 0; index < this.out.length; index++) {
      this.out[index] = (Math.max(this.out[index], floor) + 4) / 4
    }
    return this.out
  }
}
