const TERMINAL_PROTOCOL_RESPONSE = /^(?:\x1b\[[?>]?[0-9;]*[cRnt])+$/

/**
 * Responses generated by xterm while parsing terminal queries. During the
 * first fresh replay these must reach the child process, while ordinary user
 * input remains gated until replay completes.
 */
export function isTerminalProtocolResponse(data: string): boolean {
  return TERMINAL_PROTOCOL_RESPONSE.test(data)
}
