const CSI_TERMINAL_RESPONSE = String.raw`\x1b\[[?>]?[0-9;]*(?:\$y|[cRntIO])`
const OSC_COLOR_RESPONSE = String.raw`\x1b\](?:1[0-2]|4;[0-9]{1,3});(?:rgb:[0-9a-f]{1,4}(?:\/[0-9a-f]{1,4}){2}|rgba:[0-9a-f]{1,4}(?:\/[0-9a-f]{1,4}){3})(?:\x07|\x1b\\)`
const OSC_DEFAULT_COLOR_RESPONSE = new RegExp(
  String.raw`\x1b\](?:10|11);(?:rgb:[0-9a-f]{1,4}(?:\/[0-9a-f]{1,4}){2}|rgba:[0-9a-f]{1,4}(?:\/[0-9a-f]{1,4}){3})(?:\x07|\x1b\\)`,
  'i',
)
const TERMINAL_PROTOCOL_RESPONSE = new RegExp(
  `^(?:(?:${CSI_TERMINAL_RESPONSE})|(?:${OSC_COLOR_RESPONSE}))+$`,
  'i',
)

/**
 * Responses generated by xterm while parsing terminal queries. During the
 * first fresh replay these must reach the child process, while ordinary user
 * input remains gated until replay completes.
 */
export function isTerminalProtocolResponse(data: string): boolean {
  return TERMINAL_PROTOCOL_RESPONSE.test(data)
}

/**
 * Codex's native-Windows startup palette probe accepts OSC 10/11 replies for
 * only a short bounded interval. Browser/WS latency can deliver an otherwise
 * valid xterm reply after that probe has ended, at which point Codex treats the
 * reply as composer input. Codex has a console-palette fallback, so dropping
 * this optional response is safer than injecting a late one.
 */
export function shouldSuppressTerminalProtocolResponse(data: string, backend: string): boolean {
  return backend === 'codex'
    && TERMINAL_PROTOCOL_RESPONSE.test(data)
    && OSC_DEFAULT_COLOR_RESPONSE.test(data)
}
